services:

  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Request: '@=service("OxidEsales\\GdprOptinModule\\Core\\Registry").getRequest()'

  OxidEsales\GdprOptinModule\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true

  OxidEsales\GdprOptinModule\Transput\OptInRequestInterface:
    class: OxidEsales\GdprOptinModule\Transput\OptInRequest
    public: true

  OxidEsales\GdprOptinModule\Service\:
    resource: 'src/Service/*'
    public: true
