install:
  method: 'script'
  copy_script_targets: |
    vendor/oxid-esales/gdpr-optin-module/tests/scripts
  cache:
    prepared_shop: false
  container:
    options: '-e ESHOP_BOOTSTRAP_PATH=vendor/oxid-esales/oxideshop-ce/source/bootstrap.php'
  composer:
    transform: |
      {
          "minimum-stability": "dev",
          "preferred-install": {
              "oxid-esales/*": "source"
          },
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/gdpr-optin-module": "{{ .Data.global.composer.ref_name }}"
          },
          "require-dev": {
              "phpstan/phpstan": "^1.8.11",
              "squizlabs/php_codesniffer": "3.*",
              "phpmd/phpmd": "^2.11",
              "phpunit/phpunit": "^10.5",
              "codeception/codeception": "*",
              "codeception/module-asserts": "*",
              "codeception/module-db": "*",
              "codeception/module-filesystem": "*",
              "codeception/module-webdriver": "*",
              "oxid-esales/codeception-modules": "dev-b-7.1.x",
              "oxid-esales/codeception-page-objects": "dev-b-7.1.x"
          }
      }
  activate_modules:
    oegdproptin

runscript:
  matrix:
    script: |
      [
        "gdpr_module:tests-unit -d /var/www/vendor/oxid-esales/gdpr-optin-module",
        "gdpr_module:tests-integration -d /var/www/vendor/oxid-esales/gdpr-optin-module",
        "gdpr_module:tests-codeception -d /var/www/vendor/oxid-esales/gdpr-optin-module"
      ]
  container:
    options: '-e XDEBUG_MODE=coverage -e THEME_ID=apex'
    custom_script: |
     perl -pi \
          -e 's#views/twig#views/apex#g;' \
          source/vendor/oxid-esales/gdpr-optin-module/tests/Codeception/acceptance.suite.yml
  composer:
    early: skip
  gdpr_module:
    path: 'vendor/oxid-esales/gdpr-optin-module'
    workdir: 'vendor/oxid-esales/gdpr-optin-module'

runslim:
  matrix:
    script: |
      [
        "gdpr_module:phpcs -d /var/www/vendor/oxid-esales/gdpr-optin-module",
        "gdpr_module:phpstan -d /var/www/vendor/oxid-esales/gdpr-optin-module",
        "gdpr_module:phpmd -d /var/www/vendor/oxid-esales/gdpr-optin-module"
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  project_key: 'OXID-eSales_gdpr-optin-module'
  project_name: 'oxid-esales/gdpr-optin-module'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests

finish:
  slack_title: 'gdpr-optin-module ({{ .Github.RefName }}) on {{ .Github.Repository }} by {{ .Github.Actor }}'
