services:
  _defaults:
    autowire: true
    public: false

  # User address data
  address_table_data_selector:
    class: OxidEsales\GdprOptinModule\UserData\Infrastructure\GeneralTableDataSelector
    arguments:
      $selectionTable: 'oxaddress'
      $filterColumn: 'OXUSERID'
    tags:
      - { name: 'oe.gdpr.user_data' }

  # User order data
  order_table_data_selector:
    class: OxidEsales\GdprOptinModule\UserData\Infrastructure\GeneralTableDataSelector
    arguments:
      $selectionTable: 'oxorder'
      $filterColumn: 'OXUSERID'
    tags:
      - { name: 'oe.gdpr.user_data' }

  order_articles_table_data_selector:
    class: OxidEsales\GdprOptinModule\UserData\Infrastructure\RelatedTableDataSelector
    arguments:
      $primaryTable: 'oxorder'
      $selectionTable: 'oxorderarticles'
      $relationCondition: 'oxorder.OXID = oxorderarticles.OXORDERID'
      $filterColumn: 'oxorder.OXUSERID'
    tags:
      - { name: 'oe.gdpr.user_data' }

  order_files_table_data_selector:
    class: OxidEsales\GdprOptinModule\UserData\Infrastructure\RelatedTableDataSelector
    arguments:
      $primaryTable: 'oxorder'
      $selectionTable: 'oxorderfiles'
      $relationCondition: 'oxorder.OXID = oxorderarticles.OXORDERID'
      $filterColumn: 'oxorder.OXUSERID'
    tags:
      - { name: 'oe.gdpr.user_data' }