services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GdprOptinModule\UserData\Infrastructure\UserDataRepositoryInterface:
    class: OxidEsales\GdprOptinModule\UserData\Infrastructure\UserDataRepository
    public: true

  OxidEsales\GdprOptinModule\UserData\Application\AdminLogDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\AdminLogDataCollector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\AddressDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\AddressDataCollector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\NewsSubscribedDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\NewsSubscribedDataCollector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\PriceAlarmDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\PriceAlarmDataCollector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\RatingDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\RatingDataCollector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\RecommListDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\RecommListDataCollector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\RemarkDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\RemarkDataCollector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\ReviewsDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\ReviewsDataCollector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\VouchersDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\VouchersDataCollector
    arguments:
      $collectors: !tagged voucher_data_collector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\VoucherSeriesDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\VoucherSeriesDataCollector
    tags:
      - { name: 'voucher_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\UserDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\UserDataCollector
    arguments:
      $collectors: !tagged user_object_data_collector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\UserObject2GroupDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\UserObject2GroupDataCollector
    tags:
      - { name: 'user_object_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\UserObject2PaymentDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\UserObject2PaymentDataCollector
    tags:
      - { name: 'user_object_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\UserObject2RoleDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\UserObject2RoleDataCollector
    tags:
      - { name: 'user_object_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\BasketDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\BasketDataCollector
    arguments:
      $collectors: !tagged basket_data_collector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\BasketItemsDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\BasketItemsDataCollector
    tags:
      - { name: 'basket_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\OrderDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\OrderDataCollector
    arguments:
      $collectors: !tagged order_data_collector
    tags:
      - { name: 'user_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\OrderArticlesDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\OrderArticlesDataCollector
    tags:
      - { name: 'order_data_collector' }

  OxidEsales\GdprOptinModule\UserData\Application\OrderFilesDataCollector:
    class: OxidEsales\GdprOptinModule\UserData\Application\OrderFilesDataCollector
    tags:
      - { name: 'order_data_collector' }


  # User address data
  address_table_data_selector:
    class: OxidEsales\GdprOptinModule\UserData\Infrastructure\GeneralTableDataSelector
    arguments:
      $selectionTable: 'oxaddress'
      $filterColumn: 'OXUSERID'
    tags:
      - { name: 'oe.gdpr.user_data' }

  # User order data
  order_table_data_selector:
    class: OxidEsales\GdprOptinModule\UserData\Infrastructure\GeneralTableDataSelector
    arguments:
      $selectionTable: 'oxorder'
      $filterColumn: 'OXUSERID'
    tags:
      - { name: 'oe.gdpr.user_data' }

  order_articles_table_data_selector:
    class: OxidEsales\GdprOptinModule\UserData\Infrastructure\RelatedTableDataSelector
    arguments:
      $primaryTable: 'oxorder'
      $selectionTable: 'oxorderarticles'
      $relationCondition: 'oxorder.OXID = oxorderarticles.OXORDERID'
      $filterColumn: 'oxorder.OXUSERID'
    tags:
      - { name: 'oe.gdpr.user_data' }

  order_files_table_data_selector:
    class: OxidEsales\GdprOptinModule\UserData\Infrastructure\RelatedTableDataSelector
    arguments:
      $primaryTable: 'oxorder'
      $selectionTable: 'oxorderfiles'
      $relationCondition: 'oxorder.OXID = oxorderarticles.OXORDERID'
      $filterColumn: 'oxorder.OXUSERID'
    tags:
      - { name: 'oe.gdpr.user_data' }